# Generated by Django 3.1.3 on 2020-11-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buysell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('forgn_b', models.IntegerField(blank=True, null=True)),
                ('forgn_s', models.IntegerField(blank=True, null=True)),
                ('forgn_n', models.IntegerField(blank=True, null=True)),
                ('private_b', models.IntegerField(blank=True, null=True)),
                ('private_s', models.IntegerField(blank=True, null=True)),
                ('private_n', models.IntegerField(blank=True, null=True)),
                ('inst_sum_b', models.IntegerField(blank=True, null=True)),
                ('inst_sum_s', models.IntegerField(blank=True, null=True)),
                ('inst_sum_n', models.IntegerField(blank=True, null=True)),
                ('trust_b', models.IntegerField(blank=True, null=True)),
                ('trust_s', models.IntegerField(blank=True, null=True)),
                ('trust_n', models.IntegerField(blank=True, null=True)),
                ('pension_b', models.IntegerField(blank=True, null=True)),
                ('pension_s', models.IntegerField(blank=True, null=True)),
                ('pension_n', models.IntegerField(blank=True, null=True)),
                ('etc_inst_b', models.IntegerField(blank=True, null=True)),
                ('etc_inst_s', models.IntegerField(blank=True, null=True)),
                ('etc_inst_n', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('cls_prc', models.FloatField(blank=True, null=True)),
                ('trd_qty', models.IntegerField(blank=True, null=True)),
                ('trd_amt', models.IntegerField(blank=True, null=True)),
                ('etf_nav', models.FloatField(blank=True, null=True)),
                ('spread', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('per', models.FloatField(blank=True, null=True)),
                ('pbr', models.FloatField(blank=True, null=True)),
                ('pcr', models.FloatField(blank=True, null=True)),
                ('psr', models.FloatField(blank=True, null=True)),
                ('divid_yield', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('stk_kind', models.CharField(blank=True, max_length=200, null=True)),
                ('mkt_gb', models.CharField(blank=True, max_length=50, null=True)),
                ('mkt_cap', models.IntegerField(blank=True, null=True)),
                ('mkt_cap_size', models.CharField(blank=True, max_length=50, null=True)),
                ('frg_hlg', models.FloatField(blank=True, null=True)),
                ('mgt_gb', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('strt_prc', models.FloatField(blank=True, null=True)),
                ('high_prc', models.FloatField(blank=True, null=True)),
                ('low_prc', models.FloatField(blank=True, null=True)),
                ('cls_prc', models.FloatField(blank=True, null=True)),
                ('trd_qty', models.FloatField(blank=True, null=True)),
                ('trd_amt', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('comm_stk_qty', models.IntegerField(blank=True, null=True)),
                ('pref_stk_qty', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('strt_prc', models.IntegerField(blank=True, null=True)),
                ('high_prc', models.IntegerField(blank=True, null=True)),
                ('low_prc', models.IntegerField(blank=True, null=True)),
                ('cls_prc', models.IntegerField(blank=True, null=True)),
                ('adj_prc', models.BigIntegerField(blank=True, null=True)),
                ('trd_qty', models.FloatField(blank=True, null=True)),
                ('trd_amt', models.FloatField(blank=True, null=True)),
                ('shtsale_trd_qty', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
