# Generated by Django 3.1.3 on 2020-11-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_usprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usprice',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
