version: "3"

services:

  queue:
    image: rabbitmq:3-management
    container_name: rabbitmq_queue
    environment:
      - RABBITMQ_DEFAULT_USER: blended
      - RABBITMQ_DEFAULT_PASS: makeitpopweBLENDED11
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
  
  cache:
    image: redis
    container_name: redis_cache
    command: redis-server --requirepass makeitpopweBLENDED!1
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data
    restart: unless-stopped


volumes:
  cache_data:
  